### ISSUE TITLE
Wrong Page

### ISSUE THREAD

**Issue by ldx1u** [xlak/chaos#2]
When using the newest version of Chaos, at the part where you need to paste the code into the inspect window it just says " Wrong Page " only the older versions actually worked.

**Comment by xlak** [comment]
Fixed

**Comment by xlak** [comment]
In case you're wondering, it was a bug with the obfuscator. I only tested the unobfuscated code for that version (which worked) but didn't test the obfuscated result since it worked fine in the past.
